### ISSUE TITLE
Export/Import settings?

### ISSUE THREAD

**Issue by wblock** [Lord-Kamina/keybinder#17]
Please add a way to export settings to a file, and import settings from a file.  This will make it easier to transfer settings to other computers.  Thanks!

**Comment by Lord-Kamina** [comment]
I won't be adding this for a while yet to come, because handling of files from within extensions is a mess. Nevertheless, with 2.0.0, the shortcuts are stored in regular firefox preferences, so you can just copy them over.

Check out 2f1852532992c013f54510169c7378819df8efd5. It won't show on AMO for a while yet, due to the review process, but you can try it out in the releases page.
