### ISSUE TITLE
Thunderbird support

### ISSUE THREAD

**Issue by ElhemEnohpi** [Lord-Kamina/keybinder#20]
Hi, would it be possible for this addon to work in Thunderbird too?

**Comment by Lord-Kamina** [comment]
Honestly, I've never used Thunderbird so I have no idea. Probably yes with
a few modifications, I'd have to look into it.

**Comment by ElhemEnohpi** [comment]
It would be helpful for Thunderbird users if you could do that. Thunderbird has a number of single-key shortcuts, like 'a' to archive a message, or 'j' to junk it. But it often happens that you think you're typing into a mail compose window, when actually you have the message list in focus, and you start archiving or junking messages and generally making a mess of things. A lot of people would like to disable those shortcuts - some very passionately! See https://bugzilla.mozilla.org/show_bug.cgi?id=615957

I'm using "Dorando keyconfig" which works fine for me, but it's marked as "experimental", which makes it more difficult for the average user to discover and install. The original author isn't around anymore, someone else has kindly made some fixes to let it work in the current versions, but I think he can't take on the task of getting it through a full review. The "Menu Wizard" addon I think also works, but has its own issues. Other than that, your addon is the only option I've been able to find.

I'm trying to help update the official Thunderbird documentation, which currently links to an outdated incompatible version of "keyconfig". It would be great if I could point people to a simple, fully-reviewed addon as a solution to this bug/feature of Thunderbird. So if you did have the time to look into it, I think a lot of people might appreciate it. Thanks!

**Comment by Lord-Kamina** [comment]
I’m afraid it might not be possible after all, since I don’t think
Thunderbird supports JPM or most of the addon-sdk.
Not to mention, that’s only going to get worse considering the impending
move to WebExtensions…

Sorry. :/


On November 21, 2016 at 15:49:15, Elhem Enohpi (notifications@github.com)
wrote:

It would be helpful for Thunderbird users if you could do that. Thunderbird
has a number of single-key shortcuts, like 'a' to archive a message, or 'j'
to junk it. But it often happens that you think you're typing into a mail
compose window, when actually you have the message list in focus, and you
start archiving or junking messages and generally making a mess of things.
A lot of people would like to disable those shortcuts - some very
passionately! See https://bugzilla.mozilla.org/show_bug.cgi?id=615957

I'm using "Dorando keyconfig" which works fine for me, but it's marked as
"experimental", which makes it more difficult for the average user to
discover and install. The original author isn't around anymore, someone
else has kindly made some fixes to let it work in the current versions, but
I think he can't take on the task of getting it through a full review. The
"Menu Wizard" addon I think also works, but has its own issues. Other than
that, your addon is the only option I've been able to find.

I'm trying to help update the official Thunderbird documentation, which
currently links to an outdated incompatible version of "keyconfig". It
would be great if I could point people to a simple, fully-reviewed addon as
a solution to this bug/feature of Thunderbird. So if you did have the time
to look into it, I think a lot of people might appreciate it. Thanks!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Lord-Kamina/keybinder/issues/20#issuecomment-262030264>,
or mute the thread

**Comment by ElhemEnohpi** [comment]
I see, that's a shame. Thanks anyway!
