### ISSUE TITLE
Conflict with Copy Urls Expert

### ISSUE THREAD

**Issue by Keith94** [Lord-Kamina/keybinder#27]
Keybinder apparently breaks the options window of [Copy Urls Expert](https://addons.mozilla.org/en-us/firefox/addon/copy-urls-expert/) and possibly other add-ons, see https://github.com/kashiif/copy-urls-expert/issues/28#issuecomment-269248386

**Comment by Keith94** [comment]
Btw [Password Exporter](https://addons.mozilla.org/en-US/firefox/addon/password-exporter/) is also breaking because of Keybinder.

```
SyntaxError: missing ( after for  pwdex-loginmanager.js:396:28
ReferenceError: srGetStrBundle is not defined[Learn More]  pwdex-global.js:30:9
```

![firefox_2016-12-29_09-49-27](https://cloud.githubusercontent.com/assets/5490615/21550160/877d60f6-cdac-11e6-8f71-5f60c54885f0.png)

**Comment by Lord-Kamina** [comment]
I'll look into it but I'm honestly wondering how can my extension cause a
syntax error on another extension.

**Comment by Keith94** [comment]
Oh my bad, the console errors are actually unrelated to this. But there still seems to be a conflict somewhere.

**Comment by Lord-Kamina** [comment]
I'm not yet sure about Copy URLS Expert (although it certainly has at least one syntax(reference specifically) error without my add-on), but at least the case of Password exporter seems to be a poor practice on the developer's side. The issue is caused by referencing a chrome function from a js file embedded in XUL, which (if I'm correct) basically amounts to trying to access chrome (i.e. sensitive browser) functions from what is basically a content script.

I'm fairly certain using DTD files would be simpler and less prone to breakage, but eh.

**Comment by Keith94** [comment]
Hmm, should it be reported to Password Exporter devs? Here is the repo:
https://github.com/fligtar/password-exporter
