### ISSUE TITLE
multiple bindings for one action, create a new binding

### ISSUE THREAD

**Issue by cuvjoofs** [Lord-Kamina/keybinder#6]
Great project.  It seems logical that it would be possible, but I can't see how to add/create a new action/keybinding combination.  Related to this, how can multiple keybindings be assigned to the same action?  For example, if I wish to keep the keybinding F5 for reload but also add another binding for reload as well so either binding will perform the action.

Please consider this as an enhancement suggestion if it is not currently possible. 

Thank you.

**Comment by Lord-Kamina** [comment]
This is not currently possible, except for some actions that already have more than one binding assigned to them (for example, there are two reloads, as well as two of some other things)

I've actually been debating whether to do this or not for a while now... technically, it's feasible,and both parts of your request are really just the same, really, in terms of functionality. The reason I haven't done it is because it'd be very hard to do "neatly", it'd make users deal directly with XUL keys, and that could result in nasty behavior and even possibly even security issues for users.

**Comment by cuvjoofs** [comment]
Thanks for considering this idea(s).  It would be great for advanced users to have a nice interface for doing such things.  But I certainly understand your concerns.  Keep up the good work.

**Comment by Lord-Kamina** [comment]
By the way, I haven't committed anything yet but am currently experimenting with this. Be sure to check again at a later date to see whether anything comes out of it!

**Comment by cuvjoofs** [comment]
Great! Thank you.

**Comment by Lord-Kamina** [comment]
This should be fixed by 2f1852532992c013f54510169c7378819df8efd5. It won't show on AMO for a while yet, due to the review process, but you can try it out in the releases page.

**Comment by Keith94** [comment]
How is this implemented? The newest releases notes don't mention anything.

**Comment by Lord-Kamina** [comment]
You can do it by creating a new XUL key associated with the command you need (this is pretty advanced functionality, going into the firefox source-code will be required) and then assigning whatever you want to that new key.

**Comment by Keith94** [comment]
Can you possibly add an example or tutorial on the wiki here?
